// <auto-generated />
namespace NguyenTamThanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SinhVienTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SinhVienTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110050151021_SinhVienTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
